"""papers user-scoped arxiv uniqueness

Revision ID: 1d3f24c256be
Revises: 8cd7a2445b81
Create Date: 2026-09-01 16:57:44.865454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3f24c256be'
down_revision: Union[str, Sequence[str], None] = '8cd7a2445b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=False)
    op.create_unique_constraint('uq_papers_user_arxiv', 'papers', ['user_id', 'arxiv_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_papers_user_arxiv', 'papers', type_='unique')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    # ### end Alembic commands ###
